from enum import Enum

class ResponseSignal(str, Enum):

    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
   
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    PROCESSING_FAILED = "PROCESSING_FAILED"

    # NO_FILES_ERROR = "NO_FILES_ERROR"
    NOT_FOUND_FILE = "NOT_FOUND_FILE"
    FILES_ID_ERROR = "FILES_ID_ERROR"


    PROJECT_NOT_FOUND_ERROR = "PROJECT_NOT_FOUND"

    VECTOR_DB_INDEXING_ERROR = "VECTOR_DB_INDEXING_ERROR"
    INSERT_INTO_VECTOR_DB_SUCCESS = "INSERT_INTO_VECTOR_DB_SUCCESS"
    INSERT_INTO_VECTOR_DB_ERROR = "INSERT_INTO_VECTOR_DB_ERROR"

    VECTOR_DB_COLLECTION_RETRIEVE_SUCCESS = "VECTOR_DB_COLLECTION_RETRIEVE_SUCCESS"
    VECTOR_DB_COLLECTION_RETRIEVE_ERROR = "VECTOR_DB_COLLECTION_RETRIEVE_ERROR"

    VECTOR_DB_SUCCESS="VECTOR_DB_SUCCESS"
    VECTOR_DB_ERROR="VECTOR_DB_ERROR"


 
  