from enum import Enum

class ResponseSignal(str, Enum):

    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
   
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    PROCESSING_FAILED = "PROCESSING_FAILED"

    # NO_FILES_ERROR = "NO_FILES_ERROR"
    NOT_FOUND_FILE = "NOT_FOUND_FILE"
    FILES_ID_ERROR = "FILES_ID_ERROR"


 
  